### ISSUE TITLE
Undo sometimes fails

### ISSUE THREAD

**Issue by jbeuckm** [jbeuckm/strapi-plugin-import-content#18]
(node:88691) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'provider' of null
    at Object.remove (/Users/j.beuckman/Documents/blog/plugins/upload/services/Upload.js:159:14)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:88691) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:88691) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by jbeuckm** [comment]
This was probably because undo was trying to delete "null" in the list of imported items. 9fd780ea1805e82d5c376e21648fe8e7ab391c05
